### ISSUE TITLE
The rounded corner not smooth

### ISSUE THREAD

**Issue by Stupidman22** [alpbak/BoxedVerticalSeekBar#10]
Hello bro, So happy to see your project. But you can see the canvas shape rounded seem not smooth. Can you fix it ?

**Comment by Stupidman22** [comment]
As we see it seem don't have attr antialias for the rounded. Althought paint had set it ... But the path is not apply

**Comment by alpbak** [comment]
Sorry, but I can't seem to make it smoother. If you can find a solution please let me know so that I can implement it.

**Comment by alexandrobigbuho** [comment]
Hi! Instead of use a color for background and progress, implementing a drawable could be more flexible.

**Comment by Stupidman22** [comment]
Thank you so much @alexandrobigbuho , @alpbak. I will try this suggest.

**Comment by alpbak** [comment]
@alexandrobigbuho's suggestion seems like a good alternative. 👍
