### ISSUE TITLE
Component is crashing on setValue() call

### ISSUE THREAD

**Issue by losiferreira** [alpbak/BoxedVerticalSeekBar#3]
I get zero devision exception every time I call this method.

**Comment by alpbak** [comment]
Readme is updated. Please use:
dependencies {
	        compile 'com.github.alpbak:BoxedVerticalSeekBar:1b377fd8db'
	}

**Comment by behelit** [comment]
If I use the commit version 1b377fd8db, it works fine but the .setValue behaves incorrectly (which has been fixed in the latest release) but this fix doesn't seem to be available in the latest release.
