### ISSUE TITLE
setValue() doesn't work as intented

### ISSUE THREAD

**Issue by macsodev** [alpbak/BoxedVerticalSeekBar#4]
Hello,

I recently implemented your vertical seekBar, however it has an issue with method setValue()

For example: 
bv.setValue(60); results setting the value for 93. 

In your method updateProgress(), this is the line which causes the problem:

this.mPoints = (this.scrHeight - this.mPoints) * this.mMax / this.scrHeight;

edit: The seekBar is in a ConstraitLayout if that helps to reproduce the problem.

**Comment by alpbak** [comment]
Please check out the new version. Should be OK now
