### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Silvia4** [alpbak/BoxedVerticalSeekBar#7]
Hi,
I really like your SeekBar but I keep receiving this error when I add the repository following your instructions. 
```
Android resource compilation failed
Output:  .../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1390: error: duplicate value for resource 'attr/cornerRadius' with config ''.
.../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1390: error: resource previously defined here.

Command: .../.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-4818971-osx.jar/78d42767c006cb99f9fb8224dae8d739/aapt2-3.2.0-4818971-osx/aapt2 compile --legacy \
        -o \
        .../app/build/intermediates/res/merged/debug \
        .../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Daemon:  AAPT2 aapt2-3.2.0-4818971-osx Daemon #0
```

How can I solve this? Thanks

**Comment by alpbak** [comment]
Please try to change your project targetSdkVersion to 26.

**Comment by Silvia4** [comment]
I've just tried, but it keeps showing the same error.

**Comment by alpbak** [comment]
It looks like a problem with the targetSdkVersion but I can't help much without knowing some more details about your project.

**Comment by Silvia4** [comment]
I think that I've found the problem. From sdk 28 (or another one above 26) they have added in the default libraries the attribute corner radius. In stackoverflow they suggest to change the attribute name on the library that you want to add. But I don't know how can I do it in yours.
If this is true, other will have this problem using newer sdk.

**Comment by alpbak** [comment]
I've updated the project and changed the conflicting cornerRadius with libCornerRadius. There shouldn't be any problem with the latest release. Please try:

dependencies {
	    implementation 'com.github.alpbak:BoxedVerticalSeekBar:1.1.1'
	}

**Comment by Silvia4** [comment]
Perfect! Thank you very much!

**Comment by alpbak** [comment]
Then this case is closed
