### ISSUE TITLE
Failed to resolve: com.github.alpbak:BoxedVerticalSeekBar:1.1.1

### ISSUE THREAD

**Issue by SumukhaK** [alpbak/BoxedVerticalSeekBar#8]
When i add  implementation 'com.github.alpbak:BoxedVerticalSeekBar:1.1.1' in my gradle dependency and build project, I'm getting this error.
![gradle](https://user-images.githubusercontent.com/14575420/46994411-f9d6b280-d131-11e8-878d-26a38f81db34.png)

**Comment by alpbak** [comment]
Please make sure that you include
`allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}`

in your project build.gradle file
